"""first migration

Revision ID: 226320a911b8
Revises:
Create Date: 2022-05-27 01:00:41.674301

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "226320a911b8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    users_table = op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    # ### end Alembic commands ###

    op.bulk_insert(
        users_table,
        [
            {"id": 1, "first_name": "John", "last_name": "Doe", "age": 25},
            {"id": 2, "first_name": "Jane", "last_name": "Doe", "age": 30},
            {"id": 3, "first_name": "Mary", "last_name": "Smith", "age": 25},
            {"id": 4, "first_name": "Bob", "last_name": "Smith", "age": 30},
            {"id": 5, "first_name": "Mary", "last_name": "Smith", "age": 25},
            {"id": 6, "first_name": "Bob", "last_name": "Smith", "age": 30},
            {"id": 7, "first_name": "Mary", "last_name": "Smith", "age": 25},
        ],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
